In [3]:
import numpy as np

In [4]:
mat1 = np.ones((3,4))
print(mat1)
print("="*20)
mat2 = np.zeros((5,3))
print(mat2)
np.savez('np_file.npz', cat = mat1, dog = mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
v1=np.array([1,2,3,4,5])
v2=np.array([2,3,0,4,3])
np.isclose(v1,v2,atol=1)

array([ True,  True, False,  True, False])

In [3]:
import pandas as pd

In [5]:
s= pd.Series([1,2,3,4],index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64