In [3]:
import numpy as np


In [4]:
s=np.array(5)
print(s.ndim)
print(s.shape)
print("=========")
v=np.array([1,2,3,4,5,6])
print(v.ndim)
print(v.shape)
print("==========")
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m.ndim)
print(m.shape)

0
()
1
(6,)
2
(3, 3)


In [5]:
vec=np.array([1,2,3,4,5,6])
mat=vec.reshape((3,2))

print(mat.shape[1])

2


In [6]:
vac=np.array([1,2,3,4])
mat=vec.reshape((vec.shape[0],1))
mat

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
vec = np.array([1,2,3,4])
vec[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [8]:
vec = np.array([1,2,3,4])
mat = vec.reshape((vec.shape[0], 1))
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [9]:
def array_reshape(arr: list, rows:int = -1, cols:int =-1):
    
    try:
        arr = np.array(arr)
        return arr.reshape(rows,cols )
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation:{e}")

In [14]:
class c:
    x =3
o1 = c()   

In [15]:
m = np.array([[o1,2,'3'],
              [True,5,6],
              [7,8,9]])
print(m.dtype)
print(m)

object
[[<__main__.c object at 0x0000025F7F436D20> 2 '3']
 [True 5 6]
 [7 8 9]]


In [16]:
m = np.array([[1,2,'3'],
              [4,5,6],
              [7,8,9]])
fmat = m.astype(float)
print(fmat)
print(fmat.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [17]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [0,0,0]])
v = np.array([3,2,5,1])
m[-3:-1, -3:-1]

array([[4, 5],
       [7, 8]])

In [18]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
matT= mat.T
matT


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
mat = np.full((3,4),5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])