In [4]:
import numpy as np

In [4]:
s=np.array(5)
print(s.ndim)
print(s.shape)
print("=========")
v=np.array([1,2,3,4,5,6])
print(v.ndim)
print(v.shape)
print("==========")
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m.ndim)
print(m.shape)

0
()
1
(6,)
2
(3, 3)


In [21]:
vec=np.array([1,2,3,4,5,6])
mat=vec.reshape((3,2))
print(mat)
print(mat.shape[0])
print(mat.shape[1])

[[1 2]
 [3 4]
 [5 6]]
3
2


In [30]:
vec=np.array([1,2,3,4])
mat=vec.reshape((vec.shape[0],1))
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [7]:
vec = np.array([1,2,3,4])
vec[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [57]:
vec = np.array([1,2,3,4])
mat = vec.reshape((vec.shape[0], 1))
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [38]:
def array_reshape(arr: list, rows:int = -1, cols:int =-1):
    
    try:
        arr = np.array(arr)
        return arr.reshape(rows,cols )
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation:{e}")

In [41]:
vec=int(input("enter your nomber of elemenet of array"))
lis=[]
for i in range(vec):
    value=input(f"enter your value element {i+1} :")
    lis.append(value)
row=int(input("enter your rows"))    
cols=int(input("enter your cols")) 
array_reshape(lis,row,cols)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [53]:
class c:
    x =3
ol = c()   

In [54]:
m = np.array([[ol,2,'5'],
              [True,5,2],
              [7,8,9]])
print(m.dtype)
print(m)

object
[[<__main__.c object at 0x0000025BF2E97DD0> 2 '5']
 [True 5 2]
 [7 8 9]]


In [56]:
m = np.array([[1,2,'3'],
              [4,5,6],
              [7,8,9]])
fmat = m.astype(float)
print(fmat)
print(fmat.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [ ]:
#sliceing
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [0,0,0]])
v = np.array([3,2,5,1])
m[-3:-1, -3:-1]

array([[4, 5],
       [7, 8]])

In [18]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
matT= mat.T
matT


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [61]:
mat=np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
mat = np.full((3,4),5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])