In [1]:
import numpy as np

In [ ]:
#Task-1
def array_factory(mode:str, shape:int|tuple, value=None)-> np.ndarray:
    """
    Creates various NumPy arrays based on the mode
    Args:
        mode (str): The type of array to create It can be
            "zeros", "ones", "full", "identity" or other
        shape: The shape or size of the array to create
        value: The value used to full the array when mode is "full"
    Returns:
        numpy.ndarray: Returns a NumPy array according to the
        specified mode, shape, and value
    """
    if mode=="zeros":
        return np.zeros(shape)

    elif mode=="ones":
        return np.ones(shape)

    elif mode=="full":
        return np.full(shape,value)

    elif mode=="identity":
        return np.eye(shape)
    
    else:
        raise ValueError("Invalid mode")

s1=array_factory("zeros",(3,3)) 
print(s1)
print("================")
s2=array_factory("ones",(3,3)) 
print(s2)
print("================")
s3=array_factory("full",(3,3),8) 
print(s3)
print("================")
s4=array_factory("identity",3) 
print(s4)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#task-2
def secure_reshape_and_stack(data1, data2, new_shape):
    """
    Reshapes the first dataset and vertically stacks it with the second dataset.

    Args:
        data1: The first dataset that will be converted to a NumPy array
            and reshaped according to new_shape.
        data2: The second dataset that will be converted to a NumPy array
            and stacked with the reshaped first dataset.
        new_shape: The new shape used to reshape the first dataset.

    Returns:
        np.ndarray: A NumPy array containing the reshaped first dataset
        stacked vertically with the second dataset.

    Raises:
        ValueError: If the reshape or vertical stacking operation fails.
    """
    try:
        arr1=np.array(data1)
        arr2=np.array(data2)
        reshaped_arr1=arr1.reshape(new_shape)
        reshaped_arr2=arr2.reshape(new_shape)
        combined_dataset=np.vstack((reshaped_arr1,reshaped_arr2))
        return combined_dataset
    except ValueError as e:
        raise ValueError(f"company-grade Error : {e}")

data1 = [1, 2, 3, 4]

data2 = [5, 6, 7, 8]

new_shape = (2,2)
new_shape= (2,2)

result = secure_reshape_and_stack(data1, data2, new_shape)

print(result)    
    

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
